import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HNH SOFT TECH SOLUTIONS',
  description: 'Generated by create next app',
  icons: {
  icon: "https://hnh-figma-work.vercel.app/assets/HnHlogo-D9wtExhp.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
